version: '3.1'
services:
  mariadb:
    image: mariadb
    container_name: nodevader-mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nodevader
      - MYSQL_USER=nodevader
      - MYSQL_PASSWORD=nodevader
      - MYSQL_ROOT_PASSWORD=nodevader
    volumes:
      - ./server/storage/mariadb:/var/lib/mysql
      - ./server/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  # postgres:
  #   image: postgres:9.6-alpine
  #   container_name: nodevader-postgres
  #   environment:
  #     POSTGRES_PASSWORD: nodevader
  #     POSTGRES_USER: nodevader
  #     POSTGRES_DB: nodevader
  #   stdin_open: true
  #   volumes:
  #     - ./server/storage/postgresql:/var/lib/postgresql
  #   tty: true
  #   ports:
  #     - 5555:5432/tcp
  flyway:
    container_name: nodevader-mariaflyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://mariadb/nodevader -schemas=nodevader -user=nodevader -password=nodevader -connectRetries=10 migrate
    volumes:
      - ./server/migrations:/flyway/sql
    depends_on:
      - mariadb
  webserver:
    build: ./server/bin/nodejs
    image: webserver
    container_name: nodevader-webserver
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - flyway
