image: node:8

lint_and_test:
  stage: lint_and_test
  environment: Development
  only:
    - master
  script:
    - npm install
    - npm run test
    # - firebase deploy --token "$FIREBASE_TOKEN" -f
